import type { Meta, StoryObj } from '@storybook/react';
import ResponsiveFlex from '.';
declare const meta: Meta<typeof ResponsiveFlex>;
export default meta;
type Story = StoryObj<typeof ResponsiveFlex>;
export declare const Default: Story;
export declare const BreakpointTablet: Story;
export declare const RatioForFirstBoxSeventy: Story;
export declare const LargeMarginTwentyPixel: Story;
export declare const LargePaddingTwentyPixel: Story;
export declare const SmallMarginTwentyPixel: Story;
export declare const SmallPaddingTwentyPixel: Story;
