import type { Meta, StoryObj } from '@storybook/react';
import Table from '.';
declare const meta: Meta<typeof Table>;
export default meta;
type Story = StoryObj<typeof Table>;
export declare const Default: Story;
export declare const WithColumnTemplate: Story;
export declare const Dense: Story;
export declare const ManyColumns: Story;
export declare const NoData: Story;
export declare const WithUserInteraction: Story;
